version: '3.8'

services:
  # Trino Coordinator
  trino:
    image: trinodb/trino:latest
    ports:
      - "8080:8080"
    volumes:
      - ./trino-config:/etc/trino
      - ./trino-data:/data/trino
    environment:
      - TRINO_ENVIRONMENT=development
    user: root 